# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainstee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seek',
            name='which_skills_do_you_have',
            field=models.CharField(max_length=130, null=True),
        ),
        migrations.AlterField(
            model_name='seek',
            name='what_do_you_do',
            field=models.TextField(max_length=130, null=True),
        ),
    ]
