# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainstee', '0002_auto_20181024_2022'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ideas',
            new_name='Idea',
        ),
    ]
