# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-25 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainstee', '0002_auto_20181025_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seek',
            old_name='seekhelp',
            new_name='seek_help',
        ),
    ]
