# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainstee', '0003_auto_20181024_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='post',
            new_name='help',
        ),
    ]
