# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 21:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainstee', '0004_auto_20181024_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='seek',
        ),
        migrations.RemoveField(
            model_name='help',
            name='user',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='user',
        ),
        migrations.RemoveField(
            model_name='seek',
            name='user',
        ),
        migrations.DeleteModel(
            name='Help',
        ),
        migrations.DeleteModel(
            name='Idea',
        ),
        migrations.DeleteModel(
            name='Seek',
        ),
    ]
