# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainstee', '0007_idea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='Idea',
            new_name='idea',
        ),
    ]
